packages:
  - '.'

allowBuilds:
  '@google/genai': true
  '@prisma/client': true
  '@prisma/engines': true
  bcrypt: true
  esbuild: false
  msgpackr-extract: false
  prisma: true
  protobufjs: true
  workerd: false
